### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Heyula** [ggoffy/wglinks#3]
Hi @Goffy
The following error occurs when I try to install the module 

Unable to install wglinks. Error(s):
Installing wgLinks

Failed to execute xoops_module_pre_install_wglinks

**Comment by ggoffy** [comment]
working as expected

which version of XOOPS and PHP are you using

**Comment by Heyula** [comment]
XOOPS Version : XOOPS 2.5.11-Beta2
PHP Version : 7.3.33
MySQL Version : 5.5.5-10.2.41-MariaDB

**Comment by Heyula** [comment]
Upgrading the php version fixed the problem.

**Comment by ggoffy** [comment]
I fixed it also in the language files.

But: you should use min 7.4 for my modules, they are all updated for php8. if you want to use php 7.3 you have to use the previous final versions of my modules
